# Generated by Django 5.1.7 on 2025-03-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_debt_meter_meterreading_payment_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_issued',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='installation_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='reading_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
    ]
