# Generated by Django 5.1.7 on 2025-03-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_debt_due_date_alter_invoice_date_issued_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='start_date',
        ),
    ]
