# Generated by Django 5.1.7 on 2025-03-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_clients_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
