# Generated by Django 5.1.7 on 2025-03-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_complaint_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_filed',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
